import { QuizQuestion } from "@/types";

const IMG = (name: string) => `/images/${name}.jpg`;

export const QUESTIONS: QuizQuestion[] = [
  // ─── Q1: MOOD ───────────────────────────────────────────────────────────
  {
    id: "mood",
    question: 'What are you in the <span class="text-primary italic">mood</span> for?',
    label: "What are you in the mood for?",
    quote: '"Cinema is a matter of what\'s in the frame and what\'s out." — Martin Scorsese',
    gridClass: "grid-cols-1 md:grid-cols-2 lg:grid-cols-3",
    options: [
      {
        value: "comedy",
        label: "Laugh out loud",
        sub: "Comedy, satire, and lighthearted fun.",
        icon: "sentiment_very_satisfied",
        cardClass: "aspect-[4/3]",
        bgImages: [IMG("comedy-1"), IMG("comedy-2")],
        emoji: "😂",
      },
      {
        value: "emotional",
        label: "Get emotional",
        sub: "Touching dramas and heart-wrenching stories.",
        icon: "heart_broken",
        cardClass: "aspect-[4/3]",
        bgImages: [IMG("drama-1"), IMG("drama-2")],
        emoji: "😢",
      },
      {
        value: "thrill",
        label: "Feel the thrill",
        sub: "Suspense, action, and heart-pounding mystery.",
        icon: "bolt",
        cardClass: "aspect-[4/3] md:col-span-2 lg:col-span-1",
        bgImages: [IMG("thriller-1"), IMG("thriller-2")],
        emoji: "😱",
      },
      {
        value: "relax",
        label: "Relax & unwind",
        sub: "Feel-good movies and cozy visual journeys.",
        icon: "spa",
        cardClass: "aspect-[16/9] md:col-span-2",
        bgImages: [IMG("relax-1"), IMG("relax-2")],
        emoji: "😌",
      },
      {
        value: "think",
        label: "Think deeply",
        sub: "Thought-provoking documentaries and complex indies.",
        icon: "psychology",
        cardClass: "aspect-[1/1]",
        bgImages: [IMG("think-1"), IMG("think-2")],
        emoji: "🧠",
      },
    ],
  },

  // ─── Q2: COMPANY ────────────────────────────────────────────────────────
  {
    id: "company",
    question: 'Who\'s <span class="text-primary italic">watching</span> with you?',
    label: "Who's watching with you?",
    quote: '"A film is a ribbon of dreams." — Orson Welles',
    gridClass: "grid-cols-1 md:grid-cols-2",
    options: [
      {
        value: "solo",
        label: "Just me",
        sub: "A personal cinematic retreat.",
        icon: "person",
        cardClass: "aspect-[16/9]",
        bgImages: [IMG("solo-1"), IMG("solo-2")],
        emoji: "🧑",
      },
      {
        value: "partner",
        label: "Date night",
        sub: "Something for the two of you.",
        icon: "favorite",
        cardClass: "aspect-[16/9]",
        bgImages: [IMG("romance-1"), IMG("romance-2")],
        emoji: "💕",
      },
      {
        value: "family",
        label: "Family with kids",
        sub: "Universal, multi-generational picks.",
        icon: "family_restroom",
        cardClass: "aspect-[16/9]",
        bgImages: [IMG("family-1"), IMG("family-2")],
        emoji: "👨‍👩‍👧",
      },
      {
        value: "friends",
        label: "Friends",
        sub: "Group watching, energetic vibe.",
        icon: "groups",
        cardClass: "aspect-[16/9]",
        bgImages: [IMG("friends-1"), IMG("friends-2")],
        emoji: "🍻",
      },
    ],
  },

  // ─── Q3: DURATION ───────────────────────────────────────────────────────
  {
    id: "duration",
    question: 'How much <span class="text-primary italic">time</span> do you have?',
    label: "How much time do you have?",
    quote: '"The best films are those that leave you changed." — Roger Ebert',
    gridClass: "grid-cols-1 md:grid-cols-2 lg:grid-cols-4",
    options: [
      {
        value: "short",
        label: "Under 90 min",
        sub: "Quick and punchy.",
        icon: "timer",
        cardClass: "aspect-[3/4]",
        bgImages: [IMG("short-1"), IMG("short-2")],
        emoji: "⚡",
      },
      {
        value: "medium",
        label: "90 – 120 min",
        sub: "The classic runtime.",
        icon: "schedule",
        cardClass: "aspect-[3/4]",
        bgImages: [IMG("balanced-1"), IMG("cinema-1")],
        emoji: "🎬",
      },
      {
        value: "long",
        label: "Over 2 hours",
        sub: "Epic journeys welcome.",
        icon: "hourglass_top",
        cardClass: "aspect-[3/4]",
        bgImages: [IMG("long-1"), IMG("long-2")],
        emoji: "🍿",
      },
      {
        value: "any",
        label: "Doesn't matter",
        sub: "Surprise me with length.",
        icon: "all_inclusive",
        cardClass: "aspect-[3/4]",
        bgImages: [IMG("random-1"), IMG("random-2")],
        emoji: "🤷",
      },
    ],
  },

  // ─── Q4: WEIGHT ─────────────────────────────────────────────────────────
  {
    id: "weight",
    question: 'How <span class="text-primary italic">heavy</span> should it be?',
    label: "How heavy should it be?",
    quote: '"Film is not the art of scholars, but of illiterates." — Werner Herzog',
    gridClass: "grid-cols-1 md:grid-cols-3",
    options: [
      {
        value: "light",
        label: "Light & breezy",
        sub: "Easy to watch, uplifting.",
        icon: "air",
        cardClass: "aspect-[4/5]",
        bgImages: [IMG("light-1"), IMG("light-2")],
        emoji: "🌤",
      },
      {
        value: "balanced",
        label: "Somewhere in between",
        sub: "A thoughtful middle ground.",
        icon: "balance",
        cardClass: "aspect-[4/5]",
        bgImages: [IMG("balanced-1"), IMG("cinema-1")],
        emoji: "⚖️",
      },
      {
        value: "heavy",
        label: "Deep & demanding",
        sub: "Complex, emotionally dense.",
        icon: "waves",
        cardClass: "aspect-[4/5]",
        bgImages: [IMG("heavy-1"), IMG("heavy-2")],
        emoji: "🌑",
      },
    ],
  },

  // ─── Q5: ERA ────────────────────────────────────────────────────────────
  {
    id: "era",
    question: '<span class="text-primary italic">Old</span> or new?',
    label: "Old or new?",
    quote: '"Every great film should seem new every time you see it." — Roger Ebert',
    gridClass: "grid-cols-1 md:grid-cols-2 lg:grid-cols-4",
    options: [
      {
        value: "classic",
        label: "Classic",
        sub: "Pre-2000 masterpieces.",
        icon: "history_edu",
        cardClass: "aspect-[3/4]",
        bgImages: [IMG("classic-1"), IMG("classic-2")],
        emoji: "📽",
      },
      {
        value: "modern",
        label: "Modern",
        sub: "2000 – 2015 era.",
        icon: "movie",
        cardClass: "aspect-[3/4]",
        bgImages: [IMG("modern-1"), IMG("modern-2")],
        emoji: "📺",
      },
      {
        value: "recent",
        label: "Recent",
        sub: "2016 and newer.",
        icon: "auto_awesome",
        cardClass: "aspect-[3/4]",
        bgImages: [IMG("recent-1"), IMG("recent-2")],
        emoji: "✨",
      },
      {
        value: "any",
        label: "Don't care",
        sub: "Any era works.",
        icon: "all_inclusive",
        cardClass: "aspect-[3/4]",
        bgImages: [IMG("random-1"), IMG("think-2")],
        emoji: "🤷",
      },
    ],
  },

  // ─── Q6: QUALITY ────────────────────────────────────────────────────────
  {
    id: "quality",
    question: 'What kind of <span class="text-primary italic">pick</span>?',
    label: "What kind of pick?",
    quote: '"There are no rules in filmmaking. Only sins." — Frank Capra',
    gridClass: "grid-cols-1 md:grid-cols-2 lg:grid-cols-4",
    options: [
      {
        value: "hit",
        label: "Acclaimed hit",
        sub: "Critically loved, well-known.",
        icon: "star",
        cardClass: "aspect-[4/5]",
        bgImages: [IMG("acclaimed-1"), IMG("acclaimed-2")],
        emoji: "🏆",
      },
      {
        value: "gem",
        label: "Hidden gem",
        sub: "Under-the-radar brilliance.",
        icon: "diamond",
        cardClass: "aspect-[4/5]",
        bgImages: [IMG("gem-1"), IMG("gem-2")],
        emoji: "💎",
      },
      {
        value: "guilty",
        label: "Guilty pleasure",
        sub: "Fun over prestige.",
        icon: "local_fire_department",
        cardClass: "aspect-[4/5]",
        bgImages: [IMG("guilty-1"), IMG("guilty-2")],
        emoji: "🙈",
      },
      {
        value: "random",
        label: "Surprise me",
        sub: "The Curator chooses.",
        icon: "shuffle",
        cardClass: "aspect-[4/5]",
        bgImages: [IMG("random-1"), IMG("random-2")],
        emoji: "🎲",
      },
    ],
  },

  // ─── Q7: SETTING ────────────────────────────────────────────────────────
  {
    id: "setting",
    question: '<span class="text-primary italic">Where</span> are you watching?',
    label: "Where are you watching?",
    quote: '"The screen is a magic medium." — Stanley Kubrick',
    gridClass: "grid-cols-1 md:grid-cols-3",
    options: [
      {
        value: "cinema",
        label: "Cinema",
        sub: "Big screen experience.",
        icon: "theaters",
        cardClass: "aspect-[4/5]",
        bgImages: [IMG("cinema-1"), IMG("cinema-2")],
        emoji: "🎭",
      },
      {
        value: "tv",
        label: "Big TV at home",
        sub: "Couch and surround sound.",
        icon: "tv",
        cardClass: "aspect-[4/5]",
        bgImages: [IMG("tv-1"), IMG("tv-2")],
        emoji: "📺",
      },
      {
        value: "small",
        label: "Laptop / phone in bed",
        sub: "Intimate, close viewing.",
        icon: "smartphone",
        cardClass: "aspect-[4/5]",
        bgImages: [IMG("mobile-1"), IMG("mobile-2")],
        emoji: "🛋",
      },
    ],
  },
];
