import { QuizQuestion } from "@/types";

// Stable Picsum seeds give consistent images per option
const PIC = (seed: string) =>
  `https://picsum.photos/seed/${seed}/800/600`;

export const QUESTIONS: QuizQuestion[] = [
  // ─── Q1: MOOD ───────────────────────────────────────────────────────────
  {
    id: "mood",
    question: 'What are you in the <span class="text-primary italic">mood</span> for?',
    label: "What are you in the mood for?",
    quote: '"Cinema is a matter of what\'s in the frame and what\'s out." — Martin Scorsese',
    gridClass: "grid-cols-1 md:grid-cols-2 lg:grid-cols-3",
    options: [
      {
        value: "comedy",
        label: "Laugh out loud",
        sub: "Comedy, satire, and lighthearted fun.",
        icon: "sentiment_very_satisfied",
        cardClass: "aspect-[4/3]",
        bgImage: PIC("cinema-comedy"),
        emoji: "😂",
      },
      {
        value: "emotional",
        label: "Get emotional",
        sub: "Touching dramas and heart-wrenching stories.",
        icon: "heart_broken",
        cardClass: "aspect-[4/3]",
        bgImage: PIC("cinema-drama"),
        emoji: "😢",
      },
      {
        value: "thrill",
        label: "Feel the thrill",
        sub: "Suspense, action, and heart-pounding mystery.",
        icon: "bolt",
        cardClass: "aspect-[4/3] md:col-span-2 lg:col-span-1",
        bgImage: PIC("cinema-thriller"),
        emoji: "😱",
      },
      {
        value: "relax",
        label: "Relax & unwind",
        sub: "Feel-good movies and cozy visual journeys.",
        icon: "spa",
        cardClass: "aspect-[16/9] md:col-span-2",
        bgImage: PIC("cinema-relax"),
        emoji: "😌",
      },
      {
        value: "think",
        label: "Think deeply",
        sub: "Thought-provoking documentaries and complex indies.",
        icon: "psychology",
        cardClass: "aspect-[1/1]",
        bgImage: PIC("cinema-abstract"),
        emoji: "🧠",
      },
    ],
  },

  // ─── Q2: COMPANY ────────────────────────────────────────────────────────
  {
    id: "company",
    question: 'Who\'s <span class="text-primary italic">watching</span> with you?',
    label: "Who's watching with you?",
    quote: '"A film is a ribbon of dreams." — Orson Welles',
    gridClass: "grid-cols-1 md:grid-cols-2",
    options: [
      {
        value: "solo",
        label: "Just me",
        sub: "A personal cinematic retreat.",
        icon: "person",
        cardClass: "aspect-[16/9]",
        bgImage: PIC("cinema-solo"),
        emoji: "🧑",
      },
      {
        value: "partner",
        label: "Date night",
        sub: "Something for the two of you.",
        icon: "favorite",
        cardClass: "aspect-[16/9]",
        bgImage: PIC("cinema-romance"),
        emoji: "💕",
      },
      {
        value: "family",
        label: "Family with kids",
        sub: "Universal, multi-generational picks.",
        icon: "family_restroom",
        cardClass: "aspect-[16/9]",
        bgImage: PIC("cinema-family"),
        emoji: "👨‍👩‍👧",
      },
      {
        value: "friends",
        label: "Friends",
        sub: "Group watching, energetic vibe.",
        icon: "groups",
        cardClass: "aspect-[16/9]",
        bgImage: PIC("cinema-friends"),
        emoji: "🍻",
      },
    ],
  },

  // ─── Q3: DURATION ───────────────────────────────────────────────────────
  {
    id: "duration",
    question: 'How much <span class="text-primary italic">time</span> do you have?',
    label: "How much time do you have?",
    quote: '"The best films are those that leave you changed." — Roger Ebert',
    gridClass: "grid-cols-1 md:grid-cols-2 lg:grid-cols-4",
    options: [
      {
        value: "short",
        label: "Under 90 min",
        sub: "Quick and punchy.",
        icon: "timer",
        cardClass: "aspect-[3/4]",
        bgImage: PIC("cinema-short"),
        emoji: "⚡",
      },
      {
        value: "medium",
        label: "90 – 120 min",
        sub: "The classic runtime.",
        icon: "schedule",
        cardClass: "aspect-[3/4]",
        bgImage: PIC("cinema-medium"),
        emoji: "🎬",
      },
      {
        value: "long",
        label: "Over 2 hours",
        sub: "Epic journeys welcome.",
        icon: "hourglass_top",
        cardClass: "aspect-[3/4]",
        bgImage: PIC("cinema-epic"),
        emoji: "🍿",
      },
      {
        value: "any",
        label: "Doesn't matter",
        sub: "Surprise me with length.",
        icon: "all_inclusive",
        cardClass: "aspect-[3/4]",
        bgImage: PIC("cinema-any"),
        emoji: "🤷",
      },
    ],
  },

  // ─── Q4: WEIGHT ─────────────────────────────────────────────────────────
  {
    id: "weight",
    question: 'How <span class="text-primary italic">heavy</span> should it be?',
    label: "How heavy should it be?",
    quote: '"Film is not the art of scholars, but of illiterates." — Werner Herzog',
    gridClass: "grid-cols-1 md:grid-cols-3",
    options: [
      {
        value: "light",
        label: "Light & breezy",
        sub: "Easy to watch, uplifting.",
        icon: "air",
        cardClass: "aspect-[4/5]",
        bgImage: PIC("cinema-light"),
        emoji: "🌤",
      },
      {
        value: "balanced",
        label: "Somewhere in between",
        sub: "A thoughtful middle ground.",
        icon: "balance",
        cardClass: "aspect-[4/5]",
        bgImage: PIC("cinema-balanced"),
        emoji: "⚖️",
      },
      {
        value: "heavy",
        label: "Deep & demanding",
        sub: "Complex, emotionally dense.",
        icon: "waves",
        cardClass: "aspect-[4/5]",
        bgImage: PIC("cinema-heavy"),
        emoji: "🌑",
      },
    ],
  },

  // ─── Q5: ERA ────────────────────────────────────────────────────────────
  {
    id: "era",
    question: '<span class="text-primary italic">Old</span> or new?',
    label: "Old or new?",
    quote: '"Every great film should seem new every time you see it." — Roger Ebert',
    gridClass: "grid-cols-1 md:grid-cols-2 lg:grid-cols-4",
    options: [
      {
        value: "classic",
        label: "Classic",
        sub: "Pre-2000 masterpieces.",
        icon: "history_edu",
        cardClass: "aspect-[3/4]",
        bgImage: PIC("cinema-classic"),
        emoji: "📽",
      },
      {
        value: "modern",
        label: "Modern",
        sub: "2000 – 2015 era.",
        icon: "movie",
        cardClass: "aspect-[3/4]",
        bgImage: PIC("cinema-modern"),
        emoji: "📺",
      },
      {
        value: "recent",
        label: "Recent",
        sub: "2016 and newer.",
        icon: "auto_awesome",
        cardClass: "aspect-[3/4]",
        bgImage: PIC("cinema-recent"),
        emoji: "✨",
      },
      {
        value: "any",
        label: "Don't care",
        sub: "Any era works.",
        icon: "all_inclusive",
        cardClass: "aspect-[3/4]",
        bgImage: PIC("cinema-timeless"),
        emoji: "🤷",
      },
    ],
  },

  // ─── Q6: QUALITY ────────────────────────────────────────────────────────
  {
    id: "quality",
    question: 'What kind of <span class="text-primary italic">pick</span>?',
    label: "What kind of pick?",
    quote: '"There are no rules in filmmaking. Only sins." — Frank Capra',
    gridClass: "grid-cols-1 md:grid-cols-2 lg:grid-cols-4",
    options: [
      {
        value: "hit",
        label: "Acclaimed hit",
        sub: "Critically loved, well-known.",
        icon: "star",
        cardClass: "aspect-[4/5]",
        bgImage: PIC("cinema-acclaimed"),
        emoji: "🏆",
      },
      {
        value: "gem",
        label: "Hidden gem",
        sub: "Under-the-radar brilliance.",
        icon: "diamond",
        cardClass: "aspect-[4/5]",
        bgImage: PIC("cinema-gem"),
        emoji: "💎",
      },
      {
        value: "guilty",
        label: "Guilty pleasure",
        sub: "Fun over prestige.",
        icon: "local_fire_department",
        cardClass: "aspect-[4/5]",
        bgImage: PIC("cinema-guilty"),
        emoji: "🙈",
      },
      {
        value: "random",
        label: "Surprise me",
        sub: "The Curator chooses.",
        icon: "shuffle",
        cardClass: "aspect-[4/5]",
        bgImage: PIC("cinema-surprise"),
        emoji: "🎲",
      },
    ],
  },

  // ─── Q7: SETTING ────────────────────────────────────────────────────────
  {
    id: "setting",
    question: '<span class="text-primary italic">Where</span> are you watching?',
    label: "Where are you watching?",
    quote: '"The screen is a magic medium." — Stanley Kubrick',
    gridClass: "grid-cols-1 md:grid-cols-3",
    options: [
      {
        value: "cinema",
        label: "Cinema",
        sub: "Big screen experience.",
        icon: "theaters",
        cardClass: "aspect-[4/5]",
        bgImage: PIC("cinema-theater"),
        emoji: "🎭",
      },
      {
        value: "tv",
        label: "Big TV at home",
        sub: "Couch and surround sound.",
        icon: "tv",
        cardClass: "aspect-[4/5]",
        bgImage: PIC("cinema-home-tv"),
        emoji: "📺",
      },
      {
        value: "small",
        label: "Laptop / phone in bed",
        sub: "Intimate, close viewing.",
        icon: "smartphone",
        cardClass: "aspect-[4/5]",
        bgImage: PIC("cinema-mobile"),
        emoji: "🛋",
      },
    ],
  },

  // ─── Q8: EXCLUSIONS ─────────────────────────────────────────────────────
  {
    id: "exclusions",
    question: 'Anything you want to <span class="text-primary italic">avoid</span>?',
    label: "Anything you want to avoid?",
    quote: '"The screen is a magic medium. It has such power that it can retain interest as it conveys emotions and moods that no other art form can hope to tackle."',
    multiSelect: true,
    gridClass: "grid-cols-2 md:grid-cols-3",
    options: [
      {
        value: "horror",
        label: "Horror",
        icon: "skull",
        cardClass: "",
        bgImage: PIC("dark-horror"),
        emoji: "👻",
      },
      {
        value: "romance",
        label: "Romance",
        icon: "favorite",
        cardClass: "",
        bgImage: PIC("dark-romance"),
        emoji: "💝",
      },
      {
        value: "animation",
        label: "Animation",
        icon: "draw",
        cardClass: "md:row-span-2",
        bgImage: PIC("dark-animation"),
        emoji: "🎨",
      },
      {
        value: "documentary",
        label: "Documentary",
        icon: "movie_filter",
        cardClass: "",
        bgImage: PIC("dark-documentary"),
        emoji: "🎙",
      },
      {
        value: "scifi",
        label: "Sci-Fi",
        icon: "rocket_launch",
        cardClass: "",
        bgImage: PIC("dark-scifi"),
        emoji: "🚀",
      },
      {
        value: "musical",
        label: "Musical",
        icon: "music_note",
        cardClass: "",
        bgImage: PIC("dark-musical"),
        emoji: "🎵",
      },
    ],
  },
];
